version: "3"
services:
  dev:
    build:
      context: ./tvm/docker
      dockerfile: ../../docker/Dockerfile
      args:
        TIMEZONE: Asia/Tokyo
    tty: true
    working_dir: /work
    restart: always
    volumes:
      - $PWD:/work
    ports:
      - 8080:8080
      - 8889:8889
      - 8888:8888
      - 5000:5000
      - 5001:5001
      - 5002:5002
      - 5003:5003
      - 5004:5004
      - 5005:5005
      - 5006:5006
